services:
  loan_api:
    build: .
    container_name: loan_api
    ports:
      - "8000:8000"
    networks:
      - loan-net
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - loan-net
    volumes:
      # Add the :z flag to relabel the file for SELinux
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro,z
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    depends_on:
      - loan_api

networks:
  loan-net:
    # This tells compose to use an existing network
    # instead of creating a new one
    external: true

volumes:
  prometheus_data:
