[workspace]
authors = ["s0288 <alex.gansmann@hey.com>"]
channels = ["conda-forge"]
name = "ml_api"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
train-model = "python train/model.py"
fastapi = "uvicorn src.app:app --reload"
build-docker = "docker build -t loan-approval-api ."
run-docker = "docker run -p 8000:8000 loan-approval-api"

[dependencies]
python = ">=3.14.0,<3.15"
jupyterlab = ">=4.4.10,<5"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.7,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.2,<2"
fastapi = ">=0.119.1,<0.120"
uvicorn = ">=0.38.0,<0.39"
joblib = ">=1.5.2,<2"
