name: Test Feature Branches

on:
  push:
    branches:
      - "feature/**"
      - "chore/**"
      - "bugfix/**"
      - "fix/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false

      - name: Install dependencies
        run: pixi install --all

      - name: Run tests
        run: pixi run -e dev test

      - name: Generate coverage report
        run: pixi run -e dev test-cov
        continue-on-error: true
